/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type TriumphModelProps = GLTF & {
    nodes: {
        Arch_low: THREE.Mesh
        Pillar_low: THREE.Mesh
        WallDecor_low: THREE.Mesh
        Dome_low: THREE.Mesh
        Books05_low: THREE.Mesh
        Books07_low: THREE.Mesh
        Books08_low: THREE.Mesh
        Books06_low: THREE.Mesh
        Shelf_low: THREE.Mesh
        Book01_low: THREE.Mesh
        Book02_low: THREE.Mesh
        Book04_low: THREE.Mesh
        Book03_low: THREE.Mesh
        Page02_low: THREE.Mesh
        Page01_low: THREE.Mesh
        Page03_low: THREE.Mesh
        Platform_low: THREE.Mesh
        Chair_low: THREE.Mesh
        Drawer_low: THREE.Mesh
        Globe_low: THREE.Mesh
        Lamp_low: THREE.Mesh
        MidWindow_low: THREE.Mesh
        Phonograph_low: THREE.Mesh
        Table_low: THREE.Mesh
        FernPlant_low: THREE.Mesh
        Plant02_low: THREE.Mesh
        Monstera_low: THREE.Mesh
        SideWindow_low: THREE.Mesh
    }
    materials: {
        Arch: THREE.MeshStandardMaterial
        Pillar: THREE.MeshStandardMaterial
        WallDecor: THREE.MeshStandardMaterial
        Dome: THREE.MeshStandardMaterial
        Books05: THREE.MeshStandardMaterial
        Books07: THREE.MeshStandardMaterial
        Books08: THREE.MeshStandardMaterial
        Books06: THREE.MeshStandardMaterial
        Shelf: THREE.MeshStandardMaterial
        Book01: THREE.MeshStandardMaterial
        Book02: THREE.MeshStandardMaterial
        Book04: THREE.MeshStandardMaterial
        Book03: THREE.MeshStandardMaterial
        Page02: THREE.MeshStandardMaterial
        Page01: THREE.MeshStandardMaterial
        Page03: THREE.MeshStandardMaterial
        Platform: THREE.MeshStandardMaterial
        Chair: THREE.MeshStandardMaterial
        Drawer: THREE.MeshStandardMaterial
        Globe: THREE.MeshStandardMaterial
        Lamp: THREE.MeshStandardMaterial
        MidWindow: THREE.MeshStandardMaterial
        Phonograph: THREE.MeshStandardMaterial
        Table: THREE.MeshStandardMaterial
        FernPlant: THREE.MeshStandardMaterial
        Plant02: THREE.MeshStandardMaterial
        Monstera: THREE.MeshStandardMaterial
        SideWindow: THREE.MeshStandardMaterial
    }
}

export function TriumphModel(props?: Partial<TriumphModelProps>) {
    const { nodes, materials } = useGLTF('/model/Triumph2024.glb') as unknown as TriumphModelProps

    return (
        <group {...props} dispose={null}>
            <group>
                <mesh
                    name="Arch_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Arch_low.geometry}
                    material={materials.Arch}
                />
                <mesh
                    name="Pillar_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Pillar_low.geometry}
                    material={materials.Pillar}
                />
                <mesh
                    name="WallDecor_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.WallDecor_low.geometry}
                    material={materials.WallDecor}
                />
                <mesh
                    name="Dome_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Dome_low.geometry}
                    material={materials.Dome}
                />
                <mesh
                    name="Books05_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Books05_low.geometry}
                    material={materials.Books05}
                />
                <mesh
                    name="Books07_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Books07_low.geometry}
                    material={materials.Books07}
                />
                <mesh
                    name="Books08_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Books08_low.geometry}
                    material={materials.Books08}
                />
                <mesh
                    name="Books06_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Books06_low.geometry}
                    material={materials.Books06}
                />
                <mesh
                    name="Shelf_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Shelf_low.geometry}
                    material={materials.Shelf}
                />
                <mesh
                    name="Book01_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Book01_low.geometry}
                    material={materials.Book01}
                />
                <mesh
                    name="Book02_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Book02_low.geometry}
                    material={materials.Book02}
                />
                <mesh
                    name="Book04_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Book04_low.geometry}
                    material={materials.Book04}
                />
                <mesh
                    name="Book03_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Book03_low.geometry}
                    material={materials.Book03}
                />
                <mesh
                    name="Page02_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Page02_low.geometry}
                    material={materials.Page02}
                    position={[0, 0.028, 0]}
                />
                <mesh
                    name="Page01_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Page01_low.geometry}
                    material={materials.Page01}
                    position={[0, 0.024, 0]}
                />
                <mesh
                    name="Page03_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Page03_low.geometry}
                    material={materials.Page03}
                    position={[0, 0.038, 0]}
                />
                <mesh
                    name="Platform_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Platform_low.geometry}
                    material={materials.Platform}
                    position={[0, 0.031, 0]}
                />
                <mesh
                    name="Chair_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Chair_low.geometry}
                    material={materials.Chair}
                />
                <mesh
                    name="Drawer_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Drawer_low.geometry}
                    material={materials.Drawer}
                />
                <mesh
                    name="Globe_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Globe_low.geometry}
                    material={materials.Globe}
                />
                <mesh
                    name="Lamp_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Lamp_low.geometry}
                    material={materials.Lamp}
                >   <group>
                        {/* Left lamp */}
                        {/* Lamp lights */}
                        <pointLight castShadow position={[-22, 24, -2]} intensity={800} color="orange" />

                        {/* Lamp shadows */}
                        <pointLight castShadow position={[-14, 28, -8]} intensity={800} color="orange" />

                        {/* Lamp light sources */}
                        <pointLight distance={100} position={[-24, 24.5, -8]} intensity={200} color="#DADB5B" />
                        <pointLight distance={100} position={[-24, 24.5, -8]} intensity={300} color="red" />



                        {/* Right lamp */}
                        {/* Lamp lights */}
                        <pointLight castShadow position={[19, 24.5, -2]} intensity={800} color="orange" />

                        {/* Lamp shadows */}
                        <pointLight castShadow position={[14, 28, -8]} intensity={800} color="orange" />

                        {/* Lamp light sources */}
                        <pointLight distance={100} position={[24, 24.5, -8]} intensity={200} color="#DADB5B" />
                        <pointLight distance={100} position={[24, 24.5, -8]} intensity={300} color="red" />

                        <pointLight castShadow position={[0, 30, 15]} intensity={100} color="orange" />
                    </group>
                </mesh>
                <mesh
                    name="MidWindow_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.MidWindow_low.geometry}
                    material={materials.MidWindow}
                />
                <mesh
                    name="Phonograph_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Phonograph_low.geometry}
                    material={materials.Phonograph}
                />
                <mesh
                    name="Table_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Table_low.geometry}
                    material={materials.Table}
                />
                <mesh
                    name="FernPlant_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.FernPlant_low.geometry}
                    material={materials.FernPlant}
                />
                <mesh
                    name="Plant02_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plant02_low.geometry}
                    material={materials.Plant02}
                />
                <mesh
                    name="Monstera_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Monstera_low.geometry}
                    material={materials.Monstera}
                />
                <mesh
                    name="SideWindow_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.SideWindow_low.geometry}
                    material={materials.SideWindow}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/model/Triumph2024.glb')