"use client"

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import Phonograph from './objects/phonograph'
import Lamp from './objects/lamp'
import Chair from './objects/chair'

type TriumphModelProps = GLTF & {
    nodes: {
        Arch_low: THREE.Mesh
        Pillar_low: THREE.Mesh
        WallDecor_low: THREE.Mesh
        Dome_low: THREE.Mesh
        Books05_low: THREE.Mesh
        Books07_low: THREE.Mesh
        Books08_low: THREE.Mesh
        Books06_low: THREE.Mesh
        Shelf_low: THREE.Mesh
        Book01_low: THREE.Mesh
        Book02_low: THREE.Mesh
        Book04_low: THREE.Mesh
        Book03_low: THREE.Mesh
        Page02_low: THREE.Mesh
        Page01_low: THREE.Mesh
        Page03_low: THREE.Mesh
        Platform_low: THREE.Mesh
        Chair_low: THREE.Mesh
        Drawer_low: THREE.Mesh
        Globe_low: THREE.Mesh
        Lamp_low: THREE.Mesh
        MidWindow_low: THREE.Mesh
        Phonograph_low: THREE.Mesh
        Table_low: THREE.Mesh
        FernPlant_low: THREE.Mesh
        Plant02_low: THREE.Mesh
        Monstera_low: THREE.Mesh
        SideWindow_low: THREE.Mesh
    }
    materials: {
        Arch: THREE.MeshStandardMaterial
        Pillar: THREE.MeshStandardMaterial
        WallDecor: THREE.MeshStandardMaterial
        Dome: THREE.MeshStandardMaterial
        Books05: THREE.MeshStandardMaterial
        Books07: THREE.MeshStandardMaterial
        Books08: THREE.MeshStandardMaterial
        Books06: THREE.MeshStandardMaterial
        Shelf: THREE.MeshStandardMaterial
        Book01: THREE.MeshStandardMaterial
        Book02: THREE.MeshStandardMaterial
        Book04: THREE.MeshStandardMaterial
        Book03: THREE.MeshStandardMaterial
        Page02: THREE.MeshStandardMaterial
        Page01: THREE.MeshStandardMaterial
        Page03: THREE.MeshStandardMaterial
        Platform: THREE.MeshStandardMaterial
        Chair: THREE.MeshStandardMaterial
        Drawer: THREE.MeshStandardMaterial
        Globe: THREE.MeshStandardMaterial
        Lamp: THREE.MeshStandardMaterial
        MidWindow: THREE.MeshStandardMaterial
        Phonograph: THREE.MeshStandardMaterial
        Table: THREE.MeshStandardMaterial
        FernPlant: THREE.MeshStandardMaterial
        Plant02: THREE.MeshStandardMaterial
        Monstera: THREE.MeshStandardMaterial
        SideWindow: THREE.MeshStandardMaterial
    }
}

export function TriumphModel(
    props?: Partial<TriumphModelProps> & {
        focusOnObject?: (position: THREE.Vector3) => void
        resetFocus?: () => void
        isFocused?: boolean
    }
) {
    const { focusOnObject, resetFocus, isFocused } = props || {}
    const gltfData = useGLTF('/model/Triumph2024.glb') as unknown as TriumphModelProps
    const nodes = gltfData.nodes
    const materials = gltfData.materials

    return (
        <group {...props} dispose={null}>
            <group>
                <mesh
                    name="Arch_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Arch_low.geometry}
                    material={materials.Arch}
                />
                <mesh
                    name="Pillar_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Pillar_low.geometry}
                    material={materials.Pillar}
                />
                <mesh
                    name="WallDecor_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.WallDecor_low.geometry}
                    material={materials.WallDecor}
                />
                <mesh
                    name="Dome_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Dome_low.geometry}
                    material={materials.Dome}
                />
                <mesh
                    name="Books05_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Books05_low.geometry}
                    material={materials.Books05}
                />
                <mesh
                    name="Books07_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Books07_low.geometry}
                    material={materials.Books07}
                />
                <mesh
                    name="Books08_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Books08_low.geometry}
                    material={materials.Books08}
                />
                <mesh
                    name="Books06_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Books06_low.geometry}
                    material={materials.Books06}
                />
                <mesh
                    name="Shelf_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Shelf_low.geometry}
                    material={materials.Shelf}
                />
                <mesh
                    name="Book01_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Book01_low.geometry}
                    material={materials.Book01}
                />
                <mesh
                    name="Book02_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Book02_low.geometry}
                    material={materials.Book02}
                />
                <mesh
                    name="Book04_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Book04_low.geometry}
                    material={materials.Book04}
                />
                <mesh
                    name="Book03_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Book03_low.geometry}
                    material={materials.Book03}
                />
                <mesh
                    name="Page02_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Page02_low.geometry}
                    material={materials.Page02}
                    position={[0, 0.028, 0]}
                />
                <mesh
                    name="Page01_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Page01_low.geometry}
                    material={materials.Page01}
                    position={[0, 0.024, 0]}
                />
                <mesh
                    name="Page03_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Page03_low.geometry}
                    material={materials.Page03}
                    position={[0, 0.038, 0]}
                />
                <mesh
                    name="Platform_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Platform_low.geometry}
                    material={materials.Platform}
                    position={[0, 0.031, 0]}
                />
                <Chair
                    nodes={{ Chair_low: nodes.Chair_low }}
                    materials={{ Chair: materials.Chair }}
                    focusOnObject={focusOnObject}
                    resetFocus={resetFocus}
                    isFocused={isFocused}
                />
                <mesh
                    name="Drawer_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Drawer_low.geometry}
                    material={materials.Drawer}
                />
                <mesh
                    name="Globe_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Globe_low.geometry}
                    material={materials.Globe}
                />
                <Lamp nodes={{ Lamp_low: nodes.Lamp_low }} materials={{ Lamp: materials.Lamp }} />
                <mesh
                    name="MidWindow_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.MidWindow_low.geometry}
                    material={materials.MidWindow}
                />
                <Phonograph
                    nodes={{ Phonograph_low: nodes.Phonograph_low }}
                    materials={{ Phonograph: materials.Phonograph }}
                    focusOnObject={focusOnObject}
                    resetFocus={resetFocus}
                    isFocused={isFocused}
                />
                <mesh
                    name="Table_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Table_low.geometry}
                    material={materials.Table}
                />
                <mesh
                    name="FernPlant_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.FernPlant_low.geometry}
                    material={materials.FernPlant}
                />
                <mesh
                    name="Plant02_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Plant02_low.geometry}
                    material={materials.Plant02}
                />
                <mesh
                    name="Monstera_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.Monstera_low.geometry}
                    material={materials.Monstera}
                />
                <mesh
                    name="SideWindow_low"
                    castShadow
                    receiveShadow
                    geometry={nodes.SideWindow_low.geometry}
                    material={materials.SideWindow}
                />

                {/* Sun outside the window - positioned in model space */}
                <group position={[-40, 15, -70]}>
                    {/* Sun light source */}
                    <pointLight
                        castShadow
                        position={[15, 0, 5]}
                        intensity={8000}
                        color="white"
                        distance={200}
                        decay={1.9}
                    />

                    {/* Visible sun circle with glowing layers */}
                    {/* Core sun sphere */}
                    <mesh>
                        <sphereGeometry args={[5, 32, 32]} />
                        <meshStandardMaterial
                            color="white"
                            emissive="white"
                            emissiveIntensity={1}
                        />
                    </mesh>
                    {/* Inner glow layer */}
                    <mesh>
                        <sphereGeometry args={[7, 32, 32]} />
                        <meshStandardMaterial
                            color="#fff9e6"
                            emissive="#fff9e6"
                            emissiveIntensity={1}
                            transparent
                            opacity={0.6}
                        />
                    </mesh>
                    {/* Outer glow/halo */}
                    <mesh>
                        <sphereGeometry args={[9, 32, 32]} />
                        <meshStandardMaterial
                            color="#fff5cc"
                            emissive="#fff5cc"
                            emissiveIntensity={0.5}
                            transparent
                            opacity={0.3}
                        />
                    </mesh>

                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/model/Triumph2024.glb')